### ISSUE TITLE
Add a colour scheme

### ISSUE THREAD

**Issue by JBourton** [JBourton/durhack2022#1]
Add a colour scheme to the webpage using red, black and white.

[Webpage design inspiration](https://www.youtube.com/watch?v=FazgJVnrVuI&list=PLMdrbd5cbjL6r-T304Cs7NRNeu9ITb0p6&index=2)

We will need to credit the author of this video if the code is used.

**Comment by Shivansh2904** [comment]
h1 {
    color : red;
}

.main {
    color : #141414;
}

.main__container {
    display: grid;
    grid-template-columns: 1fr 1fr;
    align-items: center;
    justify-self: center;
    margin: 0 auto;
    height: 90vh;
    background-color: #141414;
    z-index: 1;
    width: 100%;
    max-width: 1300px;
    padding: 0 50px;
}

.main__content h1 {
    font-size: 4rem;
    background-color: #ff8177;
    background-image: linear-gradient(to top,#b721ff 0%, #21d4fd 100% );
    background-size: 100%;
    -webkit-background-clip: text;
    -moz-background-clip: text;
    -webkit-text-fill-color: transparent;
    -moz-text-fill-color: transparent
}

.main__content p{
    margin-top: 1rem;
    font-size: 2rem;
    font-weight: 700;
    color: #fff;
}

.main__btn{
    font-size: 1rem;
    background-image: linear-gradient(to top, #f77062 0%, #fe5196 100%);
    padding: 14px 32px;
    border: none;
    border-radius: 4px;
    color: #fff;
    margin-top: 2rem;
    cursor: pointer;
    position: relative;
    transition: all 0.35s;
    outline: none;
}

**Comment by JBourton** [comment]
This looks great, could you create a pull request of this code now?

**Comment by JBourton** [comment]
We'll also need the html code with the class attributes included to be able to incorporate this code into the project, so include that in the pull request also

**Comment by JBourton** [comment]
Issue closed as the CSS cannot be incorporated into the code without the corresponding HTML.
